services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    
    depends_on:
      - redis
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    
  celery:
    build: .
    command: celery -A convertio worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
